<div id="login-access" class="tab-pane fade active in animated shake">

    <form name="acessoSiguema" method="post" autocomplete="off" novalidate>

        <div class="form-group">
            <label for="login">C.P.F.:</label>

            <input class="form-control"
                   type="text"
                   name="cpf"
                   id="cpf"
                   required
                   placeholder="C.P.F."
                  />
        </div>

        <div class="form-group">
            <label for="senha">Senha:</label>

            <input type="password"
                   class="form-control"
                   name="senha"
                   id="senha"
                   required
                   placeholder="Senha"
                  />
        </div>

        <br/>

        <div class="form-group ">
            <button type="submit" class="btn btn-lg btn-primary btn-block">Acessar</button>
        </div>
    </form>

</div>