<div id="login-access" class="tab-pane fade active in animated shake">

    <h2>Inscrições para o IV Seminário Temático da Graduação</h2>
    <h3>Seminário sobre inclusão na Educação Superior</h3>

    <p>Para realizar sua inscrição basta informar seu CPF e senha do SigUEMA. Vagas limitadas.</p>

    <form name="acessoSiguema" method="post" autocomplete="off" novalidate>

        <div class="form-group">
            <label for="login">C.P.F.:</label>

            <input class="form-control"
                   type="text"
                   name="cpf"
                   id="cpf"
                   required
                   placeholder="C.P.F."
                  />
        </div>

        <div class="form-group">
            <label for="senha">Senha:</label>

            <input type="password"
                   class="form-control"
                   name="senha"
                   id="senha"
                   required
                   placeholder="Senha"
                  />
        </div>

        <br/>

        <div class="form-group ">
            <button type="submit" class="btn btn-lg btn-primary btn-block">Realizar Inscrição</button>
        </div>
    </form>

</div>